blinky/lib/blinky.ex
The gratuitous log messages make it hard to use the Elixir prompt when
running blinky.
I'm certainly open to alternatives, since it would be nice to demo logging. The log messages for every blink were preventing me from debugging, and I've heard that others find them annoying too.
=> Comment out log message in blinky

README.md
Updated some of the instructions for burning in the root-level README: ~~I think OS X is always going to need `sudo` for `mix.firmware burn` (and the error message without `sudo` isn't that obvious)~~; the image is built somewhere else.
=> Update burn instructions in the README (mix branch)

blinky/config/rpi3.exs
Fixes a copy'n'paste error in the rpi3 config file.
=> Correct typo

blinky/mix.exs
This appears to be a typo. My project wouldn't build until I made this correction.
=> Correct typo in :nerves_leds application

blinky/mix.exs, hello_network/mix.exs, hello_wifi/mix.exs
=> Remove redundant lines about `build_embedded` and `start_permanent`.

blinky/config/rpi3.exs
Only `/sys/class/leds/led0` exists on the Raspberry Pi 3 and it controls the green LED. It seems access was removed to accommodate the new wifi/BT capabilities.
https://github.com/raspberrypi/linux/issues/1332
http://raspberrypi.stackexchange.com/questions/44168/how-can-i-control-the-red-led-again
=> RPi3 no longer supports controlling the PWR LED.

blinky/lib/blinky.ex
Running the Blinky example on my Raspberry Pi 3, I was initially a tad underwhelmed. See the [10-second recording](https://imgur.com/e7jhYnn) of what the blinking looks like. I imagine this isn't the intended effect.
I believe the problem is that if you only have one LED, as on the RPi3, the `Blinky.blink_list_forever` loop essentially turns into the following:
Leds.set [{:green, true}]
:timer.sleep 100
Leds.set [{:green, false}]
Leds.set [{:green, true}]
:timer.sleep 100
Leds.set [{:green, false}]
Leds.set [{:green, true}]
:timer.sleep 100
Leds.set [{:green, false}]
...
That is, without the implicit delay introduced by also controlling a second LED as on other RPi boards, the one and only LED effectively never gets powered off, since there isn't a `:timer.sleep` between turning it off …
=> Improve the Blinky example for the RPi3

hello_network/lib/hello_network.ex
This pull request simply adds a trivial one-line `HelloNetwork.test_dns` function that the user can call in the IEx console to check that the Nerves host indeed has successfully established network connectivity.
The expected output when DNS resolution is available is something like this:
iex(1)> HelloNetwork.test_dns
{:ok,
{:hostent, 'nerves-project.org', [], :inet, 4,
[{192, 30, 252, 154}, {192, 30, 252, 153}]}}
=> Add a HelloNetwork.test_dns function

README.md
Just a small addition that wasn't listed in the README.md
Without it you get an error 
```➜  blinky git:(master) ✗ mix firmware.burn
** (Mix) Squash FS Tools are required to be installed on your system.
Please see https://hexdocs.pm/nerves/installation.html#host-specific-tools
for installation instructions```
=> Add squashfs to the list of OSX dependencies to be installed

hello_network/README.md
As requested by @GregMefford in #20, I've added a mention of `HelloNetwork.test_dns` to the HelloNetwork example's README, as well as improved the README a bit as a whole:
https://github.com/bendiken/nerves-examples/blob/hello_network-readme/hello_network/README.md
=> Improve HelloNetwork README

blinky/lib/blinky.ex, hello_leds/CHANGELOG.md, hello_leds/README.md, hello_leds/config/alix.exs, hello_leds/config/bbb.exs, hello_leds/config/config.exs, hello_leds/config/ev3.exs, hello_leds/config/rpi.exs, hello_leds/config/rpi2.exs, hello_leds/config/rpi3.exs, hello_leds/lib/hello_leds.ex, hello_leds/mix.exs, hello_leds/test/hello_leds_test.exs, hello_leds/test/test_helper.exs
As discussed in #29, here is a new version of blinky that uses `trigger` instead of manually setting the led on and off again.
=> Use triggers instead of infinite loops for blinky

hello_wifi/mix.exs
On a RPI and RPI2 board, usually USB WiFi dongles are used. Here the example is extended to show which module is used for the popular 8192 broadcom chipset (contained in many starter kits).
=> Add the modules for the typical USB WiFi dongles 

hello_wifi/mix.exs
Use the newer 0.13.0 system for rpi0w which supports the build-in WiFi if the required driver is loaded as a module. 
This is the change mentioned in https://github.com/nerves-project/nerves_system_rpi0/pull/7
=> Use 0.13.0 for rpi0 to support builtin WiFi with the brcmfmac driver

blinky/config/rpi0.exs, blinky/mix.exs, hello_gpio/mix.exs, hello_gpio_input/mix.exs, hello_leds/config/rpi0.exs, hello_leds/mix.exs, hello_network/mix.exs, hello_phoenix/apps/fw/mix.exs, hello_wifi/mix.exs, neopixel/mix.exs
This updates things to the latest released versions, which doesn't include OTP 20 yet, but gets us where the examples should work with OTP 19 and the latest `nerves` and `nerves_boostrap`.
=> Update system deps and nerves deps

hello_phoenix/apps/fw/mix.exs
When compiling on macOS Sierra 10.12.5, `v 0.1.0` errors when compiling:
```
==> nerves_runtime
Makefile:15: *** Nerves runtime only works on Linux. Crosscompiling is possible if $CROSSCOMPILE is set..  Stop.
could not compile dependency :nerves_runtime, "mix compile" failed. You can recompile this dependency with "mix deps.compile nerves_runtime", update it with "mix deps.update nerves_runtime" or clean it with "mix deps.clean nerves_runtime"
** (Mix) Could not compile with "make" (exit status: 2).
Depending on your OS, make sure to follow these instructions:
* Mac OS X: You need to have gcc and make installed. Try running the
commands "gcc --version" and / or "make --version". If these programs
are not installed, you will be prompted to install them.
* Linux: You need to have gcc and …
```
=> Bump nerves runtime version to 0.4.2 in hello_phoenix

.travis.yml
Homebrew doesn't make it easy to test with specific combinations of Elixir/OTP, so let's use asdf on both Linux and OSX for consistency.
=> Use asdf to manage Erlang and Elixir versions used for CI

hello_phoenix/README.md
The links to phoenix and the poncho project blog post were in the wrong format, so they weren't showing up properly. Changed to use the reference link format.
=> Fixes links in `hello_phoenix/README.md`

hello_leds/README.md
Updates the link to the Linux `/sys/class/leds` interface documentation. Looks like Free-Electrons changed their name to Bootlin.
=> Update Hello LEDs leds-class link

blinky/rel/vm.args, hello_gpio/rel/vm.args, hello_leds/rel/vm.args, hello_network/rel/vm.args, hello_phoenix/firmware/rel/vm.args
Heart has been working really well and it demonstrates one of the reliability features of the Nerves platform. Also, the new bbb builds require it since the hw watchdog is started in the Linux kernel boot sequence.
=> Enable heart on all examples

.circleci/config.yml
Downloading artifacts during `deps.get` could sometimes fail due to corrupt downloads. This PR will allow the job to retry after 5 seconds for up to 5 times. 
We can see how this catches these cases in the following job run. https://circleci.com/gh/nerves-project/nerves_examples/3283
```
=> Trying https://github.com/nerves-project/nerves_system_rpi2/releases/download/v1.5.1/nerves_system_rpi2-portable-1.5.1-D48014E.tar.gz
Invalid or corrupt file
=> Trying https://github.com/nerves-project/nerves_system_rpi2/releases/download/v1.5.1/nerves_system_rpi2-portable-1.5.1-D48014ECE742B0DA1E20A2C107CC92178F891E15CCAECA1CB9C3CDBF9CCAB9E2.tar.gz
Status 404 Not Found
** (Mix) Nerves encountered errors while validating artifact download.
gzip: …
```
=> Retry deps get on failures

hello_network/README.md, hello_network/config/config.exs
I tried to keep changes to a minimum. I was able to test wireless with an rpi0 and wired with an rpi3. Please let me know if any changes are needed.
=> Use nerves_init_gadget to configure networking

hello_gpio/README.md
Link was taking browser to a "www.nerves-project.org: 4003". error page of some kind.
=> Fix link to nerves-project.org.

blinky/README.md, hello_gpio/README.md, hello_leds/README.md, hello_network/README.md
I realized just after #117 got merged that some of this stuff wasn't consistent / updated recently.
=> Consistently assume rpi0 target by default

.circleci/config.yml
Using nerves_system_br:latest decouples from the version declared in the system mix file and causes potential host / target version mismatches.
=> Pin the circle ci container to nerves_system_br:1.7.2

.circleci/config.yml
Production firmware is about 30% smaller so it size statistics with it
are more accurate with what people will eventually see. Dev firmware is
what probably everyone who uses Nerves uses in the beginning so keep
building it too.
=> Build both dev and prod firmwares

hello_wifi/lib/hello_wifi.ex
Thanks to @petermm for bringing up a fault in the wizard start logic which would consider WiFi "configured" even if there are not networks saved (which is still valid configuration in VintageNet)
This addresses the concerns brought up in https://github.com/nerves-project/nerves_examples/pull/147 but after discussing offline, we ultimately decided just to take this opportunity to refactor with more descriptive functions to make the logic more clear and handle this specific use-case as well.
=> Refactor logic for starting the WiFi wizard

blinky/mix.exs, hello_erlang/mix.exs, hello_gpio/mix.exs, hello_leds/mix.exs, hello_lfe/mix.exs, hello_phoenix/firmware/mix.exs, hello_wifi/mix.exs, minimal/mix.exs
This will reduce the firmware size for most users by stripping
everything but the docs for dev builds.
=> Update the release config per new template

hello_phoenix/firmware/config/target.exs
This fails to connect to WiFi because `VintageNetWiFi` now explicitly expects the `:networks` key.
=> Update VintageNetWiFi config to use :networks key

hello_sqlite/README.md, hello_sqlite/lib/hello_sqlite.ex, hello_sqlite/lib/hello_sqlite/scheduler_usage_poller.ex
Make the GenServer easier to follow for developers who aren't as familiar with OTP (especially how the `handle_info(:timeout)`) is being invoked.
Add a note to the readme about the main file to look at to see sqlite actually being used.
Add code to hello_sqlite.ex that will eventually call sqlite.
Edit: I should probably note that I haven't actually tested this on a device, but I don't expect there to be any issues with the changes I made.
=> Add more info to the sqlite example application

blinky/rootfs_overlay/etc/iex.exs, hello_leds/rootfs_overlay/etc/iex.exs, hello_phoenix/firmware/rootfs_overlay/etc/iex.exs, hello_wifi/rootfs_overlay/etc/iex.exs, minimal/rootfs_overlay/etc/iex.exs
Some old examples do not have the Nerves logo in `.iex.exs`. The logo is so beautiful that there is a huge difference with or without it.
=> Add nerves logo to .iex.exs files

hello_sqlite/README.md
Fix link to `scheduler_usage_poller.ex` in README
=> fix link in README for hello_sqlite

hello_live_view/config/dev.exs
I found a typo in the live reload config of the `hello_live_view` example that was ignoring changes to both views and components.
=> Fixes a typo in the `live_reload` config of `hello_live_view` example

.circleci/config.yml, .github/dependabot.yml
For https://github.com/nerves-project/nerves/issues/918
Adds Dependabot to the project to keep examples up-to-date and a CI job which will auto merge the PR's created if CI passes
=> Add dependabot

blinky/README.md, blinky/config/grisp2.exs, blinky/config/mangopi_mq_pro.exs, blinky/config/rpi.exs, blinky/config/rpi0.exs, blinky/config/rpi2.exs, blinky/config/rpi3.exs, blinky/config/rpi3a.exs, blinky/config/rpi4.exs
Thanks to Jeff Morgan for reporting this.
=> Fix Raspberry Pi, MangoPi, and GRiSP2 LED names

hello_live_view/README.md, hello_phoenix/README.md
The poncho layout leads to a lot of code being written to move data
around between the Phoenix and hardware parts. Since this is a lot of
trouble for many projects, just point people over to the LiveView
example if they started looking in `hello_phoenix` first.
=> Update LiveView example docs and point people to it
