- hello_phoenix/apps/fw/config/config.exs
I had to have ui config in the fw project to make it run on both rpi2 and rpi3. Seems to be working with this config. Without the config the rpi refused any http connections.
> Added ui config in the fw project

- hello_phoenix/README.md
Notice a typo reading the hello_phoenix README
> Correcting typo, bye -> by

- hello_wifi/mix.exs
Tested on my Linkit Duo board.
Regards,
-Gug
> Added kernel module for linkit wifi

- hello_gpio_input/README.md
Unless I'm mistaken, the diagram is showing a pull-up resistor.
The normally-open switch will ground the pin when it's pressed,
otherwise the pin is high.
> Change text to "Pull up" instead of "Pull down"

- hello_wifi/README.md
> small typo

- .travis.yml
This brings in the new meta-misc and meta-vcs-identifier elements in case they're ever used by the examples. It also brings in many error message improvements that would be nice to have in case something goes wrong.
> Bump the fwup version used by Travis

- blinky/rel/vm.args
- hello_gpio/rel/vm.args
- hello_leds/rel/vm.args
- hello_network/rel/vm.args
- hello_phoenix/firmware/rel/vm.args
- neopixel/rel/vm.args
Catch up the examples with https://github.com/nerves-project/nerves/pull/206
> Enable ANSI colors in iex by default (per nerves PR 206)

- blinky/config/config.exs
- hello_gpio/config/config.exs
- hello_leds/config/config.exs
- hello_network/config/config.exs
- hello_phoenix/firmware/config/config.exs
- neopixel/config/config.exs
Catch up examples with https://github.com/nerves-project/nerves/pull/171
> Move bootloader config before target-specific config (nerves PR 171)

- blinky/config/config.exs
- blinky/mix.exs
- hello_gpio/config/config.exs
- hello_gpio/mix.exs
- hello_leds/config/config.exs
- hello_leds/mix.exs
- hello_network/config/config.exs
- hello_network/mix.exs
- hello_phoenix/firmware/config/config.exs
- hello_phoenix/firmware/mix.exs
- neopixel/config/config.exs
- neopixel/mix.exs
* Update all deps 
* Update project structure to use `nerves` 0.10.0 and `nerves_bootstrap` 0.8
* Fixes the state of all the apps, which were not working and broken.
> Fix all broken projects

- .circleci/config.yml
- blinky/config/config.exs
- blinky/mix.exs
- hello_gpio/config/config.exs
- hello_gpio/mix.exs
- hello_leds/config/config.exs
- hello_leds/mix.exs
- hello_network/config/config.exs
- hello_network/mix.exs
- hello_phoenix/firmware/config/config.exs
- hello_phoenix/firmware/mix.exs
This adds `nerves_init_gadget` to each of the examples.
> Init gadget

- .circleci/config.yml
- README.md
- blinky/mix.exs
- hello_gpio/mix.exs
- hello_leds/mix.exs
- hello_network/mix.exs
- hello_phoenix/firmware/mix.exs
The tests for this won't pass until the new systems have been released.
> Nerves 1.0

- hello_network/README.md
@mobileoverlord @ConnorRigby 
:)
> Add notes on distributed systems

- hello_network/README.md
- hello_network/config/config.exs
I wanted to capture this useful information in a way that felt more like a tutorial instead of notes about how one person accomplished their goal. I also noticed that there was confusion about the commented-out examples for switching to wired mode with `dhcp`, so I fixed that as well.
> Polish network distribution readme

- hello_network/README.md
> Fix typo on end of instruction.

- hello_phoenix/ui/mix.exs
First time contributing. I didn't see any kind of code of conduct or something I need to do. If there's anything I missed, please let me know.
> add missing plug_cowboy dependency

- blinky/mix.exs
- hello_gpio/mix.exs
- hello_leds/mix.exs
- hello_network/mix.exs
- hello_phoenix/firmware/mix.exs
Updated the `bbb` system to `2.0` and raises the minimum for other systems to `1.5`
> Update system versions

- blinky/README.md
> Blinky: Clarify blink rate and expectations

- .circleci/config.yml
- hello_erlang/.gitignore
- hello_erlang/README.md
- hello_erlang/config/config.exs
- hello_erlang/mix.exs
- hello_erlang/rel/vm.args.eex
- hello_erlang/src/hello_erlang_app.erl
- hello_erlang/src/hello_erlang_supervisor.erl
- hello_erlang/src/hello_erlang_worker.erl
This one is intended to be merged after the LFE one.
My Erlang is rusty and VS Code reformatted it in ways that look strange to me. I'm going to try to find an Erlanger who can be more opinionated on the code.
> Add an Erlang example project

- hello_gpio/README.md
Add some explanation as to what an LED is, why it might not work, and explain a little bit as to why a resistor is needed.
> Update the README to provide more information 

- blinky/mix.exs
- hello_gpio/mix.exs
- hello_leds/mix.exs
- hello_phoenix/firmware/mix.exs
- minimal/config/target.exs
- minimal/lib/minimal/application.ex
- minimal/mix.exs
- scripts/build-all.sh
- scripts/format-all.sh
- scripts/projects.sh
- scripts/update-deps-all.sh
These aren't very high quality scripts, but they've come in handy when
maintaining this project. The most useful is likely the one that runs `mix
deps.update` on all projects.
> Add scripts for processing projects in bulk

- README.md
> Add more projects to the top README

- hello_wifi/lib/hello_wifi.ex
for those of us copy/pasting from the example;-)
> use __MODULE__ in hello_wifi.ex

- blinky/config/config.exs
- hello_erlang/config/config.exs
- hello_gpio/config/config.exs
- hello_leds/config/config.exs
- hello_lfe/config/config.exs
- hello_phoenix/firmware/config/config.exs
- hello_snmp_agent/config/config.exs
- hello_snmp_manager/config/config.exs
- hello_sqlite/config/config.exs
- hello_wifi/config/config.exs
- hello_zig/config/config.exs
- minimal/config/config.exs
Update `config.exs` based on latest template:
https://github.com/nerves-project/nerves_bootstrap/blob/4912e728d47d53e06465aa84eb0a484589d6373f/templates/new/config/config.exs
> Update config.exs based on latest template

- hello_phoenix/ui/test/ui_web/live/page_live_test.exs
Fix test failure:
```
mix test test/ui_web/live/page_live_test.exs
1) test disconnected and connected render (UiWeb.PageLiveTest)
test/ui_web/live/page_live_test.exs:6
Assertion with =~ failed
code:  assert disconnected_html =~ "Welcome to Phoenix!"
left:  "<html lang=\"en\"><head><meta charset=\"utf-8\"/><meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"/><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/><meta content=\"HCYNJTwdGTw2USwqVAhzcm8SQgc6GxsAXqemyhaLGgbicACGXbrDiOAL\" name=\"csrf-token\"/><title data-suffix=\" · Phoenix Framework\">Ui · Phoenix Framework</title><link phx-track-static=\"phx-track-static\" rel=\"stylesheet\" href=\"/assets/app.css\"/><script defer=\"defer\" phx-track-static=\"phx-track-static\" type=\"text/javascript\" …
```
> Fix page_live_test.exs failure

- blinky/config/target.exs
- hello_erlang/config/target.exs
- hello_gpio/config/target.exs
- hello_lfe/config/target.exs
- hello_phoenix/firmware/config/target.exs
- hello_snmp_agent/config/target.exs
- hello_snmp_manager/config/target.exs
- hello_sqlite/config/target.exs
- hello_wifi/config/target.exs
- hello_zig/config/target.exs
- minimal/config/target.exs
Per update to the project template.
Related 
- https://github.com/nerves-project/nerves_bootstrap/pull/251
- https://github.com/elixir-circuits/circuits_quickstart/commit/34fee2d323fb41060ea6b1396fc9333a209d3205
> Update nerves erlinit configuration

- blinky/rel/vm.args.eex
- hello_erlang/rel/vm.args.eex
- hello_gpio/rel/vm.args.eex
- hello_live_view/rel/vm.args.eex
- hello_phoenix/firmware/rel/vm.args.eex
- hello_snmp_agent/rel/vm.args.eex
- hello_snmp_manager/rel/vm.args.eex
- hello_sqlite/rel/vm.args.eex
- hello_wifi/rel/vm.args.eex
- hello_zig/rel/vm.args.eex
- minimal/rel/vm.args.eex
* https://github.com/nerves-project/nerves_bootstrap/pull/252
* See https://www.erlang.org/doc/man/init.html#command-line-flags
> Set code_path_choice to strict for minor boot time reduction
